---
- debug:
    msg:
      - "Source: {{ cs_gjcfp_templates.src }}"
      - "Destination folder: {{ cs_gjcfp_templates.dst_src_path }}"
    verbosity: 1

- name: Pass template to subtask
  include_tasks: tasks/gen_single_java_class.yaml
  with_filetree: "{{ cs_gjcfp_templates.src }}"
  when: cs_gjcfp_file_2_handle.state == 'file'
  loop_control:
    loop_var: cs_gjcfp_file_2_handle
