---
- name: Extracting project properties from Maven pom.xml
  include_tasks: load_mvn_properties.yaml
  with_items:
    - xpath: "/ns:project/ns:groupId"
      name: group_id
    - xpath: "/ns:project/ns:artifactId"
      name: artifact_id_parent
    - xpath: "/ns:project/ns:version"
      name: version
    - xpath: "/ns:project/ns:name"
      name: project_name_parent
    - xpath: "/ns:project/ns:organization/ns:url"
      name: organization_url
  loop_control:
    loop_var: cs_lmp_xml_item

- name: "Set `artifact_id` variable from `artifact_id_parent`"
  set_fact:
    artifact_id: "{{ artifact_id_parent | replace('-parent', '') }}"

- name: "Set `project_name` variable from `project_name_parent`"
  set_fact:
    project_name: "{{ project_name_parent | replace(' Parent', '') }}"

- name: "Set `group_id_path` variable from `group_id`"
  set_fact:
    group_id_path: "{{ group_id | replace('.', '/') }}"
