---
- name: "Create '{{ cs_gjcft_item.dst | dirname }}' folder"
  file:
    state: directory
    path: "{{ cs_gjcft_item.dst | dirname }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"

- name: "Adjust '{{ cs_gjcft_item.src }}' into '{{ cs_gjcft_item.dst }}'"
  template:
    src: "{{ cs_gjcft_item.src }}"
    dest: "{{ cs_gjcft_item.dst }}"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    force: yes

