---
- name: Insert block of text after another in the file
  shell: >-
    java
    -jar {{ role_path }}/../../files/insert-unique-after.jar
    --path {{ cs_itaa_txt_item.path }}
    --insert-after "{{ cs_itaa_txt_item.insert_after }}"
    --insert-text "{{ cs_itaa_txt_item.insert_text }}"
